### ISSUE TITLE
Use a pypi version of ast-language

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_Code_Generator_FuncADL_xAOD#7]
Doing the install from git is just not great. Not portable and can't be used in all the proper places.

Places this should be removed:

- The Dockerfile
- The ci.yaml file

And then add the ast-language to the setup.py dependencies.

This can't be done until @masonproffitt pushes this guy to pypi.

**Comment by masonproffitt** [comment]
Did you see my comment on https://github.com/iris-hep/ast-language/issues/18? I can either put it on pypi as is or I can move to my suggested name and then put it on there.
